const list = [{
    text:'成为准父母',
    link:'/pages/ParentsSection',
    options:[
        {
            text:'准父母概述',
            link:''
        },
        {
            text:'代孕妈妈匹配过程',
            link:'surrogacy-matching-process'
        },
        {
            text:'卵子和精子捐献者的帮组',
            link:'egg-sperm-donation-help'
        },
        {
            text:'代孕计划和流程',
            link:'surrogacy-plan-process'
        },
        {
            text:'代孕套餐和费用',
            link:'/pages/BecomeSurrogate'
        }
    ]
},{
    text:'代孕妈妈',
    link:'/pages/BecomeSurrogate',
    options:[
        {
            text:'补偿薪资',
            link:'become-surrogate-part4-2'
        },
        {
            text:'代孕妈妈要求',
            link:'who-can-be-surrogate'
        },{
            text:'申请流程',
            link:'become-surrogate-part3'
        },{
            text:'筛选过程',
            link:'become-surrogate-part2'
        },{
            text:'经历历程',
            link:''
        }
    ]   
},{
    text:'资源',
    link:'/pages/SurrogateSection',
    options:[
        {
            text:'成为父母',
            link:'/pages/SurrogateSection'
        },
        {
            text:'成为代孕妈妈 ',
            link:'/pages/SurrogateSection'
        },{
            text:'成为捐赠者',
            link:'/pages/SurrogateSection'
        },{
            text:'寻找捐赠者',
            link:'/pages/SurrogateSection'
        },{
            text:'帮组',
            link:'/pages/SurrogateSection'
        },{
            text:'联系我们',
            link:'/pages/SurrogateSection'
        },{
            text:'咨询',
            link:'/pages/SurrogateSection'
        }
    ]   
}]

export default list